### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by Virtualmemorycode** [numq/dddating-backend#1]
thread 'main' panicked at src/main.rs:24:127:
called `Result::unwrap()` on an `Err` value: NotPresent
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by numq** [comment]
> src/main.rs:24:127

Which service is causing the error? Make sure your environment variables match those set in lib/configuration

**Comment by Virtualmemorycode** [comment]
gateway, authentication

**Comment by Virtualmemorycode** [comment]
запускаю через docker-compose, только учусь помогите мне, пожалуйста

**Comment by Virtualmemorycode** [comment]
grpcurl  -d '{"email":"test@mail.com","password":"test","role":"MODERATOR"}'    -import-path / -proto /home/test/myprochect/grpc/dddating-backend/proto/account.proto -plaintext -max-time 0.5 127.0.0.1:8080  account.AccountService/CreateAccount

Failed to dial target host "127.0.0.1:8080": context deadline exceeded
буду разбираться, в любом случае огромное спасибо

**Comment by numq** [comment]
The problem was with docker-compose - the dependent RabbitMQ services were not working properly because the hostname must match the container address. I made a couple of changes and everything should work now.
